# Generated by Django 5.2 on 2025-04-24 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('duration_days', models.PositiveIntegerField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PactStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('continue', 'Continue'), ('pause', 'Pause'), ('pivot', 'Pivot')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('pact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='api.pact')),
            ],
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('did_perform_action', models.BooleanField()),
                ('daily_note', models.TextField(blank=True, null=True)),
                ('pact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='api.pact')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('pact', 'date')},
            },
        ),
    ]
