# Generated by Django 5.2 on 2025-05-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_pact_user_firebaseuser_pact_firebase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckin',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pact',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pactstatushistory',
            name='date',
            field=models.DateField(),
        ),
    ]
