# Generated by Django 5.2 on 2025-05-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dailycheckin_date_alter_pact_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pact',
            name='current_day',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
