# Generated by Django 5.2.1 on 2025-05-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pact_current_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailycheckin',
            old_name='daily_note',
            new_name='note',
        ),
    ]
