# Generated by Django 5.2.1 on 2025-05-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_daily_note_dailycheckin_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pactstatushistory',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
